"""[info] add storage_html

Revision ID: 09a7180cb8b5
Revises: 4ff507e26b13
Create Date: 2025-01-12 11:34:24.688821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a7180cb8b5'
down_revision: Union[str, None] = '4ff507e26b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('storage_html', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'storage_html')
    # ### end Alembic commands ###
