"""RaySystem migration

Revision ID: 4918d64178d6
Revises: fc0446d32712
Create Date: 2025-02-03 17:35:35.549250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4918d64178d6'
down_revision: Union[str, None] = 'fc0446d32712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_task_id'), 'scheduled_task', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_task_tag'), 'scheduled_task', ['tag'], unique=False)
    op.create_index(op.f('ix_scheduled_task_task_type'), 'scheduled_task', ['task_type'], unique=False)
    op.create_table('task_tag_state',
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_index(op.f('ix_task_tag_state_tag'), 'task_tag_state', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_tag_state_tag'), table_name='task_tag_state')
    op.drop_table('task_tag_state')
    op.drop_index(op.f('ix_scheduled_task_task_type'), table_name='scheduled_task')
    op.drop_index(op.f('ix_scheduled_task_tag'), table_name='scheduled_task')
    op.drop_index(op.f('ix_scheduled_task_id'), table_name='scheduled_task')
    op.drop_table('scheduled_task')
    # ### end Alembic commands ###
