"""RaySystem migration

Revision ID: 760764980ad9
Revises: 1d2096bbfdff
Create Date: 2025-03-20 22:09:37.410651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760764980ad9'
down_revision: Union[str, None] = '1d2096bbfdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_children', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_note_has_children'), ['has_children'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_name', 'note', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_note_parent_id'))
        batch_op.drop_index(batch_op.f('ix_note_has_children'))
        batch_op.drop_column('has_children')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
