"""RaySystem migration

Revision ID: a0e5b18ff5c9
Revises: e3a6362f26d7
Create Date: 2025-05-10 15:04:21.861928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e5b18ff5c9'
down_revision: Union[str, None] = 'e3a6362f26d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people_name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_name_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_name_name'), ['name'], unique=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index('ix_people_name')
        batch_op.drop_index('ix_people_name2')
        batch_op.drop_index('ix_people_name3')
        batch_op.drop_index('ix_people_name4')
        batch_op.drop_index('ix_people_name5')
        batch_op.drop_column('name4')
        batch_op.drop_column('name3')
        batch_op.drop_column('name')
        batch_op.drop_column('name5')
        batch_op.drop_column('name2')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name2', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name5', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name3', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name4', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_people_name5', ['name5'], unique=False)
        batch_op.create_index('ix_people_name4', ['name4'], unique=False)
        batch_op.create_index('ix_people_name3', ['name3'], unique=False)
        batch_op.create_index('ix_people_name2', ['name2'], unique=False)
        batch_op.create_index('ix_people_name', ['name'], unique=False)

    with op.batch_alter_table('people_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_name_name'))
        batch_op.drop_index(batch_op.f('ix_people_name_id'))

    op.drop_table('people_name')
    # ### end Alembic commands ###
