"""RaySystem migration

Revision ID: ce3a41c917b1
Revises: 4918d64178d6
Create Date: 2025-03-06 00:13:44.313800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3a41c917b1'
down_revision: Union[str, None] = '4918d64178d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_task', sa.Column('schedule_type', sa.Enum('INTERVAL', 'CRON', 'EVENT', 'MANUAL', name='taskscheduletype'), server_default='interval', nullable=True))
    op.add_column('scheduled_task', sa.Column('cron_expression', sa.String(), nullable=True))
    op.add_column('scheduled_task', sa.Column('event_type', sa.String(), nullable=True))
    op.add_column('scheduled_task', sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_task', 'enabled')
    op.drop_column('scheduled_task', 'event_type')
    op.drop_column('scheduled_task', 'cron_expression')
    op.drop_column('scheduled_task', 'schedule_type')
    # ### end Alembic commands ###
