"""RaySystem migration

Revision ID: e3a6362f26d7
Revises: 711ec8f2a63c
Create Date: 2025-04-19 18:21:33.234319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a6362f26d7'
down_revision: Union[str, None] = '711ec8f2a63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('content_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_chat_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_chat_session_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_chat_session_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_chat_session_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_chat_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_chat_session_title'))
        batch_op.drop_index(batch_op.f('ix_llm_chat_session_model_name'))
        batch_op.drop_index(batch_op.f('ix_llm_chat_session_id'))

    op.drop_table('llm_chat_session')
    # ### end Alembic commands ###
