"""[site] rename url to host

Revision ID: e667c1aea8f1
Revises: 09a7180cb8b5
Create Date: 2025-01-12 14:10:35.321234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e667c1aea8f1'
down_revision: Union[str, None] = '09a7180cb8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('host', sa.String(), nullable=False))
    op.drop_index('ix_site_url', table_name='site')
    op.create_index(op.f('ix_site_host'), 'site', ['host'], unique=False)
    op.drop_column('site', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('url', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_site_host'), table_name='site')
    op.create_index('ix_site_url', 'site', ['url'], unique=False)
    op.drop_column('site', 'host')
    # ### end Alembic commands ###
