"""[site & info] unique for host and url

Revision ID: fc0446d32712
Revises: e667c1aea8f1
Create Date: 2025-01-12 16:25:27.552679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0446d32712'
down_revision: Union[str, None] = 'e667c1aea8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_info_url', table_name='info')
    op.create_index(op.f('ix_info_url'), 'info', ['url'], unique=True)
    op.drop_index('ix_site_host', table_name='site')
    op.create_index(op.f('ix_site_host'), 'site', ['host'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_host'), table_name='site')
    op.create_index('ix_site_host', 'site', ['host'], unique=False)
    op.drop_index(op.f('ix_info_url'), table_name='info')
    op.create_index('ix_info_url', 'info', ['url'], unique=False)
    # ### end Alembic commands ###
